<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Hotel;

class BrazilHotelsSeeder extends Seeder
{
    /**
     * Comodidades padrão para todos os hotéis (baseadas no Hotel Exemplo)
     */
    private function getDefaultAmenities(): array
    {
        // Usar as mesmas comodidades do Hotel Exemplo, adaptadas para português
        return [
            'wifi',
            'gym',
            'business_center',
            'restaurant',
            'bar',
            'spa',
            'concierge',
            'pool',
            'parking'
        ];
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $amenities = $this->getDefaultAmenities();
        
        $hotels = [
            // Alagoas
            [
                'name' => 'Ipioca Beach Residence',
                'location' => 'Maceió, AL',
                'city' => 'Maceió',
                'state' => 'AL',
                'address' => 'AL-101, 649 – Ipioca',
                'zip_code' => '57039-700',
                'phone' => '(82) 3321-5000',
                'email' => 'contato@ipiocabeach.com.br',
                'website' => 'https://www.ipiocabeach.com.br',
                'description' => 'Resort à beira-mar em Ipioca, Maceió, com vista para o oceano Atlântico.',
                'stars' => 4,
                'rating' => 4.5,
            ],
            [
                'name' => 'Casa Blanca Park',
                'location' => 'Maceió, AL',
                'city' => 'Maceió',
                'state' => 'AL',
                'address' => 'Av. Beira Mar, s/n',
                'zip_code' => '57000-000',
                'phone' => '(82) 3322-6000',
                'email' => 'reservas@casablancapark.com.br',
                'website' => 'https://www.casablancapark.com.br',
                'description' => 'Hotel resort com ampla estrutura de lazer e hospedagem.',
                'stars' => 4,
                'rating' => 4.3,
            ],

            // Bahia
            [
                'name' => 'Ondas Praia Resort',
                'location' => 'Porto Seguro, BA',
                'city' => 'Porto Seguro',
                'state' => 'BA',
                'address' => 'Av. Beira Mar (BR-367), nº 12.675, Km 75, Mutá',
                'zip_code' => '45810-000',
                'phone' => '(73) 3288-1000',
                'email' => 'contato@ondaspraia.com.br',
                'website' => 'https://www.vivantecobeach.com.br',
                'description' => 'Resort à beira-mar em Porto Seguro com estrutura completa de lazer.',
                'stars' => 5,
                'rating' => 4.7,
            ],
            [
                'name' => 'Casa Blanca Park Hotel',
                'location' => 'Porto Seguro, BA',
                'city' => 'Porto Seguro',
                'state' => 'BA',
                'address' => 'Av. 22 de Abril, 435 – Centro',
                'zip_code' => '45810-000',
                'phone' => '(73) 3288-2000',
                'email' => 'reservas@casablancapark.com.br',
                'website' => 'https://www.casablancapark.com.br',
                'description' => 'Hotel no centro de Porto Seguro com fácil acesso às praias.',
                'stars' => 4,
                'rating' => 4.4,
            ],
            [
                'name' => 'Vivant Ecobeach Resort',
                'location' => 'Maraú, BA',
                'city' => 'Maraú',
                'state' => 'BA',
                'address' => 'Barra Grande — Taipus de Fora',
                'zip_code' => '45520-000',
                'phone' => '(73) 3258-3000',
                'email' => 'contato@vivantecobeach.com.br',
                'website' => 'https://www.vivantecobeach.com.br',
                'description' => 'Resort ecológico em Barra Grande, uma das praias mais belas da Bahia.',
                'stars' => 5,
                'rating' => 4.8,
            ],
            [
                'name' => 'Makaira Beach Resort',
                'location' => 'Canavieiras, BA',
                'city' => 'Canavieiras',
                'state' => 'BA',
                'address' => 'Ilha de Atalaia',
                'zip_code' => '45860-000',
                'phone' => '(73) 3284-4000',
                'email' => 'reservas@makaira.com.br',
                'website' => 'https://www.makaira.com.br',
                'description' => 'Resort exclusivo na Ilha de Atalaia, entre o Rio Patipe e o Oceano Atlântico.',
                'stars' => 5,
                'rating' => 4.6,
            ],
            [
                'name' => 'Tree Bies Resort',
                'location' => 'Entre Rios, BA',
                'city' => 'Entre Rios',
                'state' => 'BA',
                'address' => 'Praia de Subaúma — Lot. Miramar',
                'zip_code' => '48190-000',
                'phone' => '(75) 3431-5000',
                'email' => 'contato@treebies.com.br',
                'website' => 'https://www.treebies.com.br',
                'description' => 'Resort na Praia de Subaúma com estrutura completa de lazer.',
                'stars' => 4,
                'rating' => 4.5,
            ],

            // Ceará
            [
                'name' => 'Dom Pedro Laguna',
                'location' => 'Aquiraz, CE',
                'city' => 'Aquiraz',
                'state' => 'CE',
                'address' => 'Av. Marginal do Empreendimento Aquiraz Riviera, s/n – Praia da Marambaia',
                'zip_code' => '61700-000',
                'phone' => '(85) 3361-6000',
                'email' => 'reservas@dompedrolaguna.com.br',
                'website' => 'https://www.dompedrolaguna.com.br',
                'description' => 'Resort na Praia da Marambaia com vista para o mar e lagoa.',
                'stars' => 5,
                'rating' => 4.7,
            ],
            [
                'name' => 'The Coral Beach Resort',
                'location' => 'Trairi, CE',
                'city' => 'Trairi',
                'state' => 'CE',
                'address' => 'Praia de Guajiru / Flecheiras — Rua 01, S/N, Lotes 3 e 4',
                'zip_code' => '62690-000',
                'phone' => '(85) 3315-7000',
                'email' => 'contato@coralbeach.com.br',
                'website' => 'https://www.coralbeach.com.br',
                'description' => 'Resort nas praias de Guajiru e Flecheiras, uma das mais belas do Ceará.',
                'stars' => 5,
                'rating' => 4.6,
            ],

            // Maranhão
            [
                'name' => 'Gran Lençóis Flat Residence',
                'location' => 'Barreirinhas, MA',
                'city' => 'Barreirinhas',
                'state' => 'MA',
                'address' => 'Estrada de São Domingos, s/n — Povoado Boa Vista',
                'zip_code' => '65590-000',
                'phone' => '(98) 3349-8000',
                'email' => 'reservas@granlencois.com.br',
                'website' => 'https://www.granlencoisflat.com',
                'description' => 'Flat residence próximo aos Lençóis Maranhenses, uma das maravilhas naturais do Brasil.',
                'stars' => 4,
                'rating' => 4.4,
            ],

            // Paraíba
            [
                'name' => 'Infinity at The Sea',
                'location' => 'João Pessoa, PB',
                'city' => 'João Pessoa',
                'state' => 'PB',
                'address' => 'Av. Cabo Branco, 1780 – Cabo Branco',
                'zip_code' => '58045-010',
                'phone' => '(83) 3247-9000',
                'email' => 'contato@infinityatthesea.com.br',
                'website' => 'https://www.infinityatthesea.com.br',
                'description' => 'Hotel à beira-mar em Cabo Branco, João Pessoa.',
                'stars' => 4,
                'rating' => 4.5,
            ],
            [
                'name' => 'Asenza Beach Resort',
                'location' => 'Pitimbú, PB',
                'city' => 'Pitimbú',
                'state' => 'PB',
                'address' => 'Litoral sul da Paraíba, ao lado da Barra do rio Abiaí',
                'zip_code' => '58324-000',
                'phone' => '(83) 3298-1000',
                'email' => 'reservas@asenza.com.br',
                'website' => 'https://www.asenzabeachresort.com.br',
                'description' => 'Resort no litoral sul da Paraíba, próximo à Barra do rio Abiaí.',
                'stars' => 5,
                'rating' => 4.6,
            ],

            // Pernambuco
            [
                'name' => 'Porto Alto Resort',
                'location' => 'Ipojuca, PE',
                'city' => 'Ipojuca',
                'state' => 'PE',
                'address' => 'Rua MA 01, Lote 02-B, s/n – em frente à Praia de Muro Alto',
                'zip_code' => '55900-000',
                'phone' => '(81) 3552-2000',
                'email' => 'contato@portoalto.com.br',
                'website' => 'https://www.portoaltoresort.com.br',
                'description' => 'Resort em frente à Praia de Muro Alto, próximo a Porto de Galinhas.',
                'stars' => 5,
                'rating' => 4.7,
            ],
            [
                'name' => 'Porto 2 Life Resort',
                'location' => 'Ipojuca, PE',
                'city' => 'Ipojuca',
                'state' => 'PE',
                'address' => 'Praia de Muro Alto / Porto de Galinhas',
                'zip_code' => '55900-000',
                'phone' => '(81) 3552-3000',
                'email' => 'reservas@porto2life.com.br',
                'website' => 'https://www.porto2life.com.br',
                'description' => 'Resort na região de Porto de Galinhas, uma das praias mais famosas do Brasil.',
                'stars' => 5,
                'rating' => 4.8,
            ],

            // Piauí
            [
                'name' => 'Vila Atlântica / Vila Atlântida',
                'location' => 'Luís Correia, PI',
                'city' => 'Luís Correia',
                'state' => 'PI',
                'address' => 'Rua José de Freitas, região da Praia de Atalaia',
                'zip_code' => '64220-000',
                'phone' => '(86) 3263-4000',
                'email' => 'contato@vilatlantica.com.br',
                'website' => 'https://www.vilatlantica.com.br',
                'description' => 'Complexo de flats na Praia de Atalaia, Luís Correia.',
                'stars' => 4,
                'rating' => 4.3,
            ],

            // Rio Grande do Norte
            [
                'name' => 'Bello Mare Hotel',
                'location' => 'Natal, RN',
                'city' => 'Natal',
                'state' => 'RN',
                'address' => 'Av. Engenheiro Roberto Freire, 4917 – Ponta Negra',
                'zip_code' => '59090-000',
                'phone' => '(84) 3209-5000',
                'email' => 'reservas@bellomare.com.br',
                'website' => 'https://www.redeandradebellomare.com.br',
                'description' => 'Hotel em Ponta Negra, uma das praias mais famosas de Natal.',
                'stars' => 4,
                'rating' => 4.5,
            ],
            [
                'name' => 'Rio das Garças Ecoresort',
                'location' => 'São José de Mipibu, RN',
                'city' => 'São José de Mipibu',
                'state' => 'RN',
                'address' => 'Região de São José de Mipibu',
                'zip_code' => '59162-000',
                'phone' => '(84) 3218-6000',
                'email' => 'contato@riodasgarcas.com.br',
                'website' => 'https://www.riodasgarcasecoresort.com.br',
                'description' => 'Ecoresort com foco em sustentabilidade e contato com a natureza.',
                'stars' => 4,
                'rating' => 4.4,
            ],
            [
                'name' => 'Vila do Mar',
                'location' => 'Natal, RN',
                'city' => 'Natal',
                'state' => 'RN',
                'address' => 'Av. Praia de Ponta Negra, s/n',
                'zip_code' => '59090-000',
                'phone' => '(84) 3209-7000',
                'email' => 'reservas@viladomar.com.br',
                'website' => 'https://www.viladomar.com.br',
                'description' => 'Resort all inclusive em Natal com estrutura completa de lazer.',
                'stars' => 5,
                'rating' => 4.7,
            ],

            // Goiás
            [
                'name' => 'Encontro das Águas',
                'location' => 'Caldas Novas, GO',
                'city' => 'Caldas Novas',
                'state' => 'GO',
                'address' => 'Av. Caminho do Lago c/ Alameda Chico Batata, Jardim Metodista',
                'zip_code' => '75690-000',
                'phone' => '(64) 3453-8000',
                'email' => 'reservas@encontrodasaguas.com.br',
                'website' => 'https://www.encontro-das-aguas.caldasnovashotels.com',
                'description' => 'Resort em Caldas Novas com águas termais e estrutura completa.',
                'stars' => 5,
                'rating' => 4.6,
            ],
            [
                'name' => 'Evian Thermas Residence',
                'location' => 'Caldas Novas, GO',
                'city' => 'Caldas Novas',
                'state' => 'GO',
                'address' => 'Rua Presidente Kennedy, 194-236',
                'zip_code' => '75690-000',
                'phone' => '(64) 3453-9000',
                'email' => 'contato@evianthermas.com.br',
                'website' => 'https://www.evianthermas.com.br',
                'description' => 'Residence com águas termais em Caldas Novas.',
                'stars' => 4,
                'rating' => 4.4,
            ],
            [
                'name' => 'Privê Ilhas do Lago / Ilhas do Lago Eco Resort',
                'location' => 'Caldas Novas, GO',
                'city' => 'Caldas Novas',
                'state' => 'GO',
                'address' => 'Av. Caminho do Lago, s/n',
                'zip_code' => '75690-000',
                'phone' => '(64) 3454-1000',
                'email' => 'reservas@ilhasdolago.com.br',
                'website' => 'https://www.ilhasdolagocaldasnovas.com.br',
                'description' => 'Eco resort em Caldas Novas com foco em sustentabilidade.',
                'stars' => 5,
                'rating' => 4.7,
            ],
            [
                'name' => 'Lagoa EcoTower / Lagoa Eco Towers',
                'location' => 'Caldas Novas, GO',
                'city' => 'Caldas Novas',
                'state' => 'GO',
                'address' => 'Próximo à Av. Lagoa Quente',
                'zip_code' => '75690-000',
                'phone' => '(64) 3454-2000',
                'email' => 'contato@lagoaecotower.com.br',
                'website' => 'https://www.lagoaecotower.com.br',
                'description' => 'Torre residencial com vista para a Lagoa Quente.',
                'stars' => 4,
                'rating' => 4.5,
            ],
            [
                'name' => 'Mandala dos Pyrineus',
                'location' => 'Pirenópolis, GO',
                'city' => 'Pirenópolis',
                'state' => 'GO',
                'address' => 'Estrada para Pirenópolis, s/n',
                'zip_code' => '72980-000',
                'phone' => '(62) 3331-3000',
                'email' => 'reservas@mandalapyrineus.com.br',
                'website' => 'https://www.wamexperience.com.br',
                'description' => 'Eco village em Pirenópolis com foco em bem-estar e natureza.',
                'stars' => 4,
                'rating' => 4.4,
            ],
            [
                'name' => 'Marina Flat & Náutica / Marina Flat',
                'location' => 'Caldas Novas, GO',
                'city' => 'Caldas Novas',
                'state' => 'GO',
                'address' => 'Avenida Caminho do Lago / margens do Lago Corumbá',
                'zip_code' => '75690-000',
                'phone' => '(64) 3454-3000',
                'email' => 'contato@marinaflat.com.br',
                'website' => 'https://www.marinaflat.com.br',
                'description' => 'Flat náutico às margens do Lago Corumbá.',
                'stars' => 4,
                'rating' => 4.3,
            ],
            [
                'name' => 'Alta Vista Thermas Resort',
                'location' => 'Caldas Novas, GO',
                'city' => 'Caldas Novas',
                'state' => 'GO',
                'address' => 'Rua 18, Qd 68, Lt 1-R – Bairro Turista II',
                'zip_code' => '75690-000',
                'phone' => '(64) 3454-4000',
                'email' => 'reservas@altavista.com.br',
                'website' => 'https://www.altavistathermasresort.com.br',
                'description' => 'Resort com águas termais e vista panorâmica.',
                'stars' => 5,
                'rating' => 4.6,
            ],
            [
                'name' => 'Quinta Santa Bárbara Ecoresort',
                'location' => 'Pirenópolis, GO',
                'city' => 'Pirenópolis',
                'state' => 'GO',
                'address' => 'Rua do Bonfim, nº 1',
                'zip_code' => '72980-000',
                'phone' => '(62) 3331-4000',
                'email' => 'contato@quintasantabarbara.com.br',
                'website' => 'https://www.quintasantabarbara.com.br',
                'description' => 'Ecoresort em Pirenópolis com arquitetura colonial.',
                'stars' => 4,
                'rating' => 4.5,
            ],
            [
                'name' => 'Serra Madre Hotel',
                'location' => 'Rio Quente, GO',
                'city' => 'Rio Quente',
                'state' => 'GO',
                'address' => 'Av. Principal, s/n',
                'zip_code' => '75695-000',
                'phone' => '(64) 3455-5000',
                'email' => 'reservas@serramadre.com.br',
                'website' => 'https://www.serramadre.com.br',
                'description' => 'Hotel em Rio Quente com acesso às águas termais.',
                'stars' => 4,
                'rating' => 4.4,
            ],
            [
                'name' => 'Atrium Thermas Residence Service',
                'location' => 'Caldas Novas, GO',
                'city' => 'Caldas Novas',
                'state' => 'GO',
                'address' => 'Avenida Coronel Cirilo Lopes de Morais, 33',
                'zip_code' => '75690-000',
                'phone' => '(64) 3454-6000',
                'email' => 'contato@atriumthermas.com.br',
                'website' => 'https://www.prive-atrium-thermas-residence-service-caldas-novas.caldasnovashotels.com',
                'description' => 'Residence service com águas termais em Caldas Novas.',
                'stars' => 4,
                'rating' => 4.3,
            ],
            [
                'name' => 'Best Western Suítes Le Jardin',
                'location' => 'Caldas Novas, GO',
                'city' => 'Caldas Novas',
                'state' => 'GO',
                'address' => 'Rua Machado de Assis, nº 555 — Bairro Bandeirantes',
                'zip_code' => '75690-000',
                'phone' => '(64) 3454-7000',
                'email' => 'reservas@lejardin.com.br',
                'website' => 'https://www.bestwestern.com.br',
                'description' => 'Hotel da rede Best Western em Caldas Novas.',
                'stars' => 4,
                'rating' => 4.5,
            ],
            [
                'name' => 'Golden Dolphin Grand Hotel',
                'location' => 'Caldas Novas, GO',
                'city' => 'Caldas Novas',
                'state' => 'GO',
                'address' => 'Av. Elias Bufaiçal, Gleba 01',
                'zip_code' => '75690-000',
                'phone' => '(64) 3454-8000',
                'email' => 'reservas@goldendolphin.com.br',
                'website' => 'https://www.goldendolphin.com.br',
                'description' => 'Grand hotel em Caldas Novas com estrutura completa.',
                'stars' => 5,
                'rating' => 4.7,
            ],
            [
                'name' => 'Golden Dolphin Supreme',
                'location' => 'Caldas Novas, GO',
                'city' => 'Caldas Novas',
                'state' => 'GO',
                'address' => 'Av. Principal, s/n',
                'zip_code' => '75690-000',
                'phone' => '(64) 3454-9000',
                'email' => 'contato@goldendolphinsupreme.com.br',
                'website' => 'https://www.goldendolphinsupreme.com.br',
                'description' => 'Hotel da rede Golden Dolphin em Caldas Novas.',
                'stars' => 5,
                'rating' => 4.6,
            ],
            [
                'name' => 'Hotspring B3 Hotels',
                'location' => 'Caldas Novas, GO',
                'city' => 'Caldas Novas',
                'state' => 'GO',
                'address' => 'Rua Dona Francisca Alla Cunha, 152 – Bairro Turista I',
                'zip_code' => '75690-000',
                'phone' => '(64) 3455-1000',
                'email' => 'reservas@hotsprings.com.br',
                'website' => 'https://www.hotsprings.com.br',
                'description' => 'Hotel com águas termais em Caldas Novas.',
                'stars' => 4,
                'rating' => 4.4,
            ],
            [
                'name' => 'Jardins da Lagoa / Jardins da Lagoa CondoResort',
                'location' => 'Caldas Novas, GO',
                'city' => 'Caldas Novas',
                'state' => 'GO',
                'address' => 'Av. Lagoa Quente, 5',
                'zip_code' => '75690-000',
                'phone' => '(64) 3455-2000',
                'email' => 'contato@jardinsdalagoa.com.br',
                'website' => 'https://www.lagoaparquesehoteis.com.br',
                'description' => 'CondoResort às margens da Lagoa Quente.',
                'stars' => 5,
                'rating' => 4.6,
            ],
            [
                'name' => 'Privê Praias do Lago Ecoresort',
                'location' => 'Caldas Novas, GO',
                'city' => 'Caldas Novas',
                'state' => 'GO',
                'address' => 'Av. Caminho do Lago, Gleba 04 – Jardim Interlago',
                'zip_code' => '75690-000',
                'phone' => '(64) 3455-3000',
                'email' => 'reservas@praiado lago.com.br',
                'website' => 'https://www.wamhoteis.com.br',
                'description' => 'Ecoresort às margens do lago em Caldas Novas.',
                'stars' => 5,
                'rating' => 4.7,
            ],
            [
                'name' => 'Toulon Park Residence Resort',
                'location' => 'Caldas Novas, GO',
                'city' => 'Caldas Novas',
                'state' => 'GO',
                'address' => 'Av. das Nações, Quadra 19, Lote 1R',
                'zip_code' => '75690-000',
                'phone' => '(64) 3455-4000',
                'email' => 'contato@toulonpark.com.br',
                'website' => 'https://www.toulonpark.com.br',
                'description' => 'Residence resort em Caldas Novas.',
                'stars' => 4,
                'rating' => 4.4,
            ],
            [
                'name' => 'Prive Riviera Park Hotel',
                'location' => 'Caldas Novas, GO',
                'city' => 'Caldas Novas',
                'state' => 'GO',
                'address' => 'Av. Deputado Jamel Cecílio, nº 2690',
                'zip_code' => '75690-000',
                'phone' => '(64) 3455-6000',
                'email' => 'reservas@rivierapark.com.br',
                'website' => 'https://www.wamhoteis.com.br',
                'description' => 'Hotel da rede WAM em Caldas Novas.',
                'stars' => 4,
                'rating' => 4.5,
            ],

            // Espírito Santo
            [
                'name' => 'China Park',
                'location' => 'Domingos Martins, ES',
                'city' => 'Domingos Martins',
                'state' => 'ES',
                'address' => 'Região de Pedra Azul',
                'zip_code' => '29260-000',
                'phone' => '(27) 3268-7000',
                'email' => 'contato@chinapark.com.br',
                'website' => 'https://www.chinaparkecoresort.com.br',
                'description' => 'Eco resort nas Montanhas Capixabas, próximo à Pedra Azul.',
                'stars' => 4,
                'rating' => 4.5,
            ],
            [
                'name' => 'Vista Azul Hotel',
                'location' => 'Domingos Martins, ES',
                'city' => 'Domingos Martins',
                'state' => 'ES',
                'address' => 'Pedra Azul',
                'zip_code' => '29260-000',
                'phone' => '(27) 3268-8000',
                'email' => 'reservas@vistaazul.com.br',
                'website' => 'https://www.vistaazulhotel.com.br',
                'description' => 'Hotel nas Montanhas Capixabas com vista para a Pedra Azul.',
                'stars' => 4,
                'rating' => 4.4,
            ],

            // Minas Gerais
            [
                'name' => 'Náutico Clube Fronteira',
                'location' => 'Fronteira, MG',
                'city' => 'Fronteira',
                'state' => 'MG',
                'address' => 'Rod. BR-153, Km 231',
                'zip_code' => '38230-000',
                'phone' => '(34) 3351-9000',
                'email' => 'contato@nauticoclubefronteira.com.br',
                'website' => 'https://www.nauticoclubefronteira.com.br',
                'description' => 'Clube náutico em Fronteira, Minas Gerais.',
                'stars' => 4,
                'rating' => 4.3,
            ],
            [
                'name' => 'Pousada Terramare',
                'location' => 'Guapé, MG',
                'city' => 'Guapé',
                'state' => 'MG',
                'address' => 'Condomínio Terramare Península',
                'zip_code' => '37177-000',
                'phone' => '(35) 3551-1000',
                'email' => 'reservas@terramare.com.br',
                'website' => 'https://www.pousadaterramare.com.br',
                'description' => 'Pousada no Condomínio Terramare Península.',
                'stars' => 4,
                'rating' => 4.4,
            ],

            // Rio de Janeiro
            [
                'name' => 'Búzios Beach Resort',
                'location' => 'Armação dos Búzios, RJ',
                'city' => 'Armação dos Búzios',
                'state' => 'RJ',
                'address' => 'Avenida dos Tucuns – Praia de Tucuns',
                'zip_code' => '28950-000',
                'phone' => '(22) 2623-2000',
                'email' => 'reservas@buziosresort.com.br',
                'website' => 'https://www.buziosresort.com.br',
                'description' => 'Resort na Praia de Tucuns, Búzios.',
                'stars' => 5,
                'rating' => 4.7,
            ],
            [
                'name' => 'Hotel Nacional',
                'location' => 'Rio de Janeiro, RJ',
                'city' => 'Rio de Janeiro',
                'state' => 'RJ',
                'address' => 'Av. Niemeyer, 769 – São Conrado',
                'zip_code' => '22450-220',
                'phone' => '(21) 2103-3000',
                'email' => 'reservas@hotelnacionalriodejaneiro.com',
                'website' => 'https://www.hotelnacionalriodejaneiro.com',
                'description' => 'Hotel em São Conrado com vista para o mar.',
                'stars' => 5,
                'rating' => 4.8,
            ],
            [
                'name' => 'Livyd Angra dos Reis',
                'location' => 'Angra dos Reis, RJ',
                'city' => 'Angra dos Reis',
                'state' => 'RJ',
                'address' => 'Rodovia BR-101, Km 533 – Mambucaba',
                'zip_code' => '23900-000',
                'phone' => '(24) 3365-4000',
                'email' => 'contato@livyd.com.br',
                'website' => 'https://www.livyd.com.br',
                'description' => 'Resort em Angra dos Reis, região entre Angra e Paraty.',
                'stars' => 5,
                'rating' => 4.6,
            ],
            [
                'name' => 'Aldeia das Águas Park Resort Quartier',
                'location' => 'Barra do Piraí, RJ',
                'city' => 'Barra do Piraí',
                'state' => 'RJ',
                'address' => 'Complexo Aldeia das Águas',
                'zip_code' => '27100-000',
                'phone' => '(24) 2443-5000',
                'email' => 'reservas@aldeiadasaguas.com.br',
                'website' => 'https://www.aldeiadasaguas.com.br',
                'description' => 'Complexo resort com parque aquático em Barra do Piraí.',
                'stars' => 5,
                'rating' => 4.7,
            ],
            [
                'name' => 'Angra Beach Hotel',
                'location' => 'Angra dos Reis, RJ',
                'city' => 'Angra dos Reis',
                'state' => 'RJ',
                'address' => 'Rua José Watanabe, 111 – Parque das Palmeiras',
                'zip_code' => '23906-520',
                'phone' => '(24) 3365-6000',
                'email' => 'contato@angrabeach.com',
                'website' => 'https://www.angrabeach.com',
                'description' => 'Hotel à beira-mar em Angra dos Reis.',
                'stars' => 4,
                'rating' => 4.5,
            ],
            [
                'name' => 'Plaza Barra First / Plaza Rio Residences Barra First',
                'location' => 'Rio de Janeiro, RJ',
                'city' => 'Rio de Janeiro',
                'state' => 'RJ',
                'address' => 'Av. das Américas, 7897 — Barra da Tijuca',
                'zip_code' => '22793-081',
                'phone' => '(21) 2103-7000',
                'email' => 'reservas@plazabarra.com.br',
                'website' => 'https://www.redeplaza.com.br',
                'description' => 'Hotel da rede Plaza na Barra da Tijuca.',
                'stars' => 5,
                'rating' => 4.6,
            ],
            [
                'name' => 'Bendito Cacao Resort & Spa',
                'location' => 'Campos do Jordão, SP',
                'city' => 'Campos do Jordão',
                'state' => 'SP',
                'address' => 'Av. Principal, s/n',
                'zip_code' => '12460-000',
                'phone' => '(12) 3668-8000',
                'email' => 'reservas@benditocacao.com.br',
                'website' => 'https://www.benditocacao.com.br',
                'description' => 'Resort & Spa em Campos do Jordão (anteriormente Blue Mountain Resort & Spa).',
                'stars' => 5,
                'rating' => 4.7,
            ],
        ];

        $created = 0;
        $skipped = 0;

        foreach ($hotels as $hotelData) {
            // Verificar se o hotel já existe
            $existing = Hotel::where('name', $hotelData['name'])->first();
            
            if (!$existing) {
                Hotel::create([
                    'name' => $hotelData['name'],
                    'location' => $hotelData['location'],
                    'city' => $hotelData['city'],
                    'state' => $hotelData['state'],
                    'address' => $hotelData['address'],
                    'zip_code' => $hotelData['zip_code'],
                    'phone' => $hotelData['phone'],
                    'email' => $hotelData['email'],
                    'website' => $hotelData['website'] ?? null,
                    'description' => $hotelData['description'],
                    'amenities' => $amenities,
                    'stars' => $hotelData['stars'],
                    'rating' => $hotelData['rating'],
                    'is_active' => true,
                    'is_functioning' => true,
                ]);
                $created++;
            } else {
                $skipped++;
            }
        }

        $this->command->info("Hotéis cadastrados: {$created}");
        $this->command->info("Hotéis já existentes (ignorados): {$skipped}");
        $this->command->info('Total de hotéis processados: ' . count($hotels));
    }
}

